// Code generated by MockGen. DO NOT EDIT.
// Source: cte.sql.go
//
// Generated by this command:
//
//	mockgen -source=cte.sql.go -destination=mock/cte.sql.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	db "example/db"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCteQuerier is a mock of CteQuerier interface.
type MockCteQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockCteQuerierMockRecorder
	isgomock struct{}
}

// MockCteQuerierMockRecorder is the mock recorder for MockCteQuerier.
type MockCteQuerierMockRecorder struct {
	mock *MockCteQuerier
}

// NewMockCteQuerier creates a new mock instance.
func NewMockCteQuerier(ctrl *gomock.Controller) *MockCteQuerier {
	mock := &MockCteQuerier{ctrl: ctrl}
	mock.recorder = &MockCteQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCteQuerier) EXPECT() *MockCteQuerierMockRecorder {
	return m.recorder
}

// DeleteUserAndReturnOrders mocks base method.
func (m *MockCteQuerier) DeleteUserAndReturnOrders(ctx context.Context, arg1 db.DBTX, arg db.DeleteUserAndReturnOrdersParams) ([]db.DeleteUserAndReturnOrdersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserAndReturnOrders", ctx, arg1, arg)
	ret0, _ := ret[0].([]db.DeleteUserAndReturnOrdersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUserAndReturnOrders indicates an expected call of DeleteUserAndReturnOrders.
func (mr *MockCteQuerierMockRecorder) DeleteUserAndReturnOrders(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserAndReturnOrders", reflect.TypeOf((*MockCteQuerier)(nil).DeleteUserAndReturnOrders), ctx, arg1, arg)
}

// GetActiveUsersWithSubquery mocks base method.
func (m *MockCteQuerier) GetActiveUsersWithSubquery(ctx context.Context, arg1 db.DBTX) ([]db.GetActiveUsersWithSubqueryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveUsersWithSubquery", ctx, arg1)
	ret0, _ := ret[0].([]db.GetActiveUsersWithSubqueryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveUsersWithSubquery indicates an expected call of GetActiveUsersWithSubquery.
func (mr *MockCteQuerierMockRecorder) GetActiveUsersWithSubquery(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveUsersWithSubquery", reflect.TypeOf((*MockCteQuerier)(nil).GetActiveUsersWithSubquery), ctx, arg1)
}

// GetAllEntities mocks base method.
func (m *MockCteQuerier) GetAllEntities(ctx context.Context, arg1 db.DBTX) ([]db.GetAllEntitiesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllEntities", ctx, arg1)
	ret0, _ := ret[0].([]db.GetAllEntitiesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllEntities indicates an expected call of GetAllEntities.
func (mr *MockCteQuerierMockRecorder) GetAllEntities(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllEntities", reflect.TypeOf((*MockCteQuerier)(nil).GetAllEntities), ctx, arg1)
}

// GetExclusiveHighValueUsers mocks base method.
func (m *MockCteQuerier) GetExclusiveHighValueUsers(ctx context.Context, arg1 db.DBTX) ([]db.GetExclusiveHighValueUsersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExclusiveHighValueUsers", ctx, arg1)
	ret0, _ := ret[0].([]db.GetExclusiveHighValueUsersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExclusiveHighValueUsers indicates an expected call of GetExclusiveHighValueUsers.
func (mr *MockCteQuerierMockRecorder) GetExclusiveHighValueUsers(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExclusiveHighValueUsers", reflect.TypeOf((*MockCteQuerier)(nil).GetExclusiveHighValueUsers), ctx, arg1)
}

// GetRevenueGrowth mocks base method.
func (m *MockCteQuerier) GetRevenueGrowth(ctx context.Context, arg1 db.DBTX, arg db.GetRevenueGrowthParams) ([]db.GetRevenueGrowthRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRevenueGrowth", ctx, arg1, arg)
	ret0, _ := ret[0].([]db.GetRevenueGrowthRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRevenueGrowth indicates an expected call of GetRevenueGrowth.
func (mr *MockCteQuerierMockRecorder) GetRevenueGrowth(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRevenueGrowth", reflect.TypeOf((*MockCteQuerier)(nil).GetRevenueGrowth), ctx, arg1, arg)
}

// GetTopSpenders mocks base method.
func (m *MockCteQuerier) GetTopSpenders(ctx context.Context, arg1 db.DBTX, arg db.GetTopSpendersParams) ([]db.GetTopSpendersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopSpenders", ctx, arg1, arg)
	ret0, _ := ret[0].([]db.GetTopSpendersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopSpenders indicates an expected call of GetTopSpenders.
func (mr *MockCteQuerierMockRecorder) GetTopSpenders(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopSpenders", reflect.TypeOf((*MockCteQuerier)(nil).GetTopSpenders), ctx, arg1, arg)
}

// GetUserCohortRetention mocks base method.
func (m *MockCteQuerier) GetUserCohortRetention(ctx context.Context, arg1 db.DBTX) ([]db.GetUserCohortRetentionRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCohortRetention", ctx, arg1)
	ret0, _ := ret[0].([]db.GetUserCohortRetentionRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCohortRetention indicates an expected call of GetUserCohortRetention.
func (mr *MockCteQuerierMockRecorder) GetUserCohortRetention(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCohortRetention", reflect.TypeOf((*MockCteQuerier)(nil).GetUserCohortRetention), ctx, arg1)
}

// GetUserRank mocks base method.
func (m *MockCteQuerier) GetUserRank(ctx context.Context, arg1 db.DBTX, arg db.GetUserRankParams) (*db.GetUserRankRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRank", ctx, arg1, arg)
	ret0, _ := ret[0].(*db.GetUserRankRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRank indicates an expected call of GetUserRank.
func (mr *MockCteQuerierMockRecorder) GetUserRank(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRank", reflect.TypeOf((*MockCteQuerier)(nil).GetUserRank), ctx, arg1, arg)
}

// GetUserSpendingTiers mocks base method.
func (m *MockCteQuerier) GetUserSpendingTiers(ctx context.Context, arg1 db.DBTX) ([]db.GetUserSpendingTiersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserSpendingTiers", ctx, arg1)
	ret0, _ := ret[0].([]db.GetUserSpendingTiersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserSpendingTiers indicates an expected call of GetUserSpendingTiers.
func (mr *MockCteQuerierMockRecorder) GetUserSpendingTiers(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSpendingTiers", reflect.TypeOf((*MockCteQuerier)(nil).GetUserSpendingTiers), ctx, arg1)
}

// GetUserTiersBySubquery mocks base method.
func (m *MockCteQuerier) GetUserTiersBySubquery(ctx context.Context, arg1 db.DBTX) ([]db.GetUserTiersBySubqueryRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTiersBySubquery", ctx, arg1)
	ret0, _ := ret[0].([]db.GetUserTiersBySubqueryRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTiersBySubquery indicates an expected call of GetUserTiersBySubquery.
func (mr *MockCteQuerierMockRecorder) GetUserTiersBySubquery(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTiersBySubquery", reflect.TypeOf((*MockCteQuerier)(nil).GetUserTiersBySubquery), ctx, arg1)
}

// GetUsersWithOrderTotals mocks base method.
func (m *MockCteQuerier) GetUsersWithOrderTotals(ctx context.Context, arg1 db.DBTX) ([]db.GetUsersWithOrderTotalsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersWithOrderTotals", ctx, arg1)
	ret0, _ := ret[0].([]db.GetUsersWithOrderTotalsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersWithOrderTotals indicates an expected call of GetUsersWithOrderTotals.
func (mr *MockCteQuerierMockRecorder) GetUsersWithOrderTotals(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersWithOrderTotals", reflect.TypeOf((*MockCteQuerier)(nil).GetUsersWithOrderTotals), ctx, arg1)
}

// GetUsersWithOrders mocks base method.
func (m *MockCteQuerier) GetUsersWithOrders(ctx context.Context, arg1 db.DBTX) ([]db.GetUsersWithOrdersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersWithOrders", ctx, arg1)
	ret0, _ := ret[0].([]db.GetUsersWithOrdersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersWithOrders indicates an expected call of GetUsersWithOrders.
func (mr *MockCteQuerierMockRecorder) GetUsersWithOrders(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersWithOrders", reflect.TypeOf((*MockCteQuerier)(nil).GetUsersWithOrders), ctx, arg1)
}

// SearchUsersWithStats mocks base method.
func (m *MockCteQuerier) SearchUsersWithStats(ctx context.Context, arg1 db.DBTX, arg db.SearchUsersWithStatsParams) ([]db.SearchUsersWithStatsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsersWithStats", ctx, arg1, arg)
	ret0, _ := ret[0].([]db.SearchUsersWithStatsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsersWithStats indicates an expected call of SearchUsersWithStats.
func (mr *MockCteQuerierMockRecorder) SearchUsersWithStats(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsersWithStats", reflect.TypeOf((*MockCteQuerier)(nil).SearchUsersWithStats), ctx, arg1, arg)
}

// TransferUserOrders mocks base method.
func (m *MockCteQuerier) TransferUserOrders(ctx context.Context, arg1 db.DBTX, arg db.TransferUserOrdersParams) ([]db.TransferUserOrdersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferUserOrders", ctx, arg1, arg)
	ret0, _ := ret[0].([]db.TransferUserOrdersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferUserOrders indicates an expected call of TransferUserOrders.
func (mr *MockCteQuerierMockRecorder) TransferUserOrders(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferUserOrders", reflect.TypeOf((*MockCteQuerier)(nil).TransferUserOrders), ctx, arg1, arg)
}

// UpsertAndReturnUser mocks base method.
func (m *MockCteQuerier) UpsertAndReturnUser(ctx context.Context, arg1 db.DBTX, arg db.UpsertAndReturnUserParams) (*db.UpsertAndReturnUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertAndReturnUser", ctx, arg1, arg)
	ret0, _ := ret[0].(*db.UpsertAndReturnUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertAndReturnUser indicates an expected call of UpsertAndReturnUser.
func (mr *MockCteQuerierMockRecorder) UpsertAndReturnUser(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertAndReturnUser", reflect.TypeOf((*MockCteQuerier)(nil).UpsertAndReturnUser), ctx, arg1, arg)
}
