// Code generated by MockGen. DO NOT EDIT.
// Source: search.sql.go
//
// Generated by this command:
//
//	mockgen -source=search.sql.go -destination=mock/search.sql.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	db "example/db"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSearchQuerier is a mock of SearchQuerier interface.
type MockSearchQuerier struct {
	ctrl     *gomock.Controller
	recorder *MockSearchQuerierMockRecorder
	isgomock struct{}
}

// MockSearchQuerierMockRecorder is the mock recorder for MockSearchQuerier.
type MockSearchQuerierMockRecorder struct {
	mock *MockSearchQuerier
}

// NewMockSearchQuerier creates a new mock instance.
func NewMockSearchQuerier(ctrl *gomock.Controller) *MockSearchQuerier {
	mock := &MockSearchQuerier{ctrl: ctrl}
	mock.recorder = &MockSearchQuerierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchQuerier) EXPECT() *MockSearchQuerierMockRecorder {
	return m.recorder
}

// SearchUsers mocks base method.
func (m *MockSearchQuerier) SearchUsers(ctx context.Context, arg1 db.DBTX, arg db.SearchUsersParams) ([]*db.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchUsers", ctx, arg1, arg)
	ret0, _ := ret[0].([]*db.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchUsers indicates an expected call of SearchUsers.
func (mr *MockSearchQuerierMockRecorder) SearchUsers(ctx, arg1, arg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchUsers", reflect.TypeOf((*MockSearchQuerier)(nil).SearchUsers), ctx, arg1, arg)
}
