//go:generate mockgen -source=$GOFILE -destination=mock/$GOFILE -package=mock

// Code generated by sqlc. DO NOT EDIT.
// source: cte.sql

package db

import (
	"context"
	"errors"
	"time"

	tracing "example"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

func NewCteQueries() *CteQueries {
	return &CteQueries{}
}

type CteQueries struct {
}

const DeleteUserAndReturnOrders = `-- name: DeleteUserAndReturnOrders :many
WITH deleted_user AS (
    DELETE FROM orders WHERE user_id = $1 RETURNING id, user_id, amount, status, created_at
)
SELECT id, user_id, amount, status, created_at FROM deleted_user
`

type DeleteUserAndReturnOrdersParams struct {
	UserID int64
}

type DeleteUserAndReturnOrdersRow struct {
	ID        int64
	UserID    int64
	Amount    decimal.Decimal
	Status    string
	CreatedAt time.Time
}

func (q *CteQueries) DeleteUserAndReturnOrders(ctx context.Context, db DBTX, arg DeleteUserAndReturnOrdersParams) ([]DeleteUserAndReturnOrdersRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.DeleteUserAndReturnOrders")
	defer tracer.End()
	rows, err := db.Query(ctx, DeleteUserAndReturnOrders, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteUserAndReturnOrdersRow
	for rows.Next() {
		var i DeleteUserAndReturnOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetActiveUsersWithSubquery = `-- name: GetActiveUsersWithSubquery :many
WITH user_activity AS (
    SELECT u.id as user_id, u.name,
           (SELECT COUNT(*) FROM orders o WHERE o.user_id = u.id) as order_count,
           (SELECT COALESCE(SUM(o.amount), 0) FROM orders o WHERE o.user_id = u.id) as total_spent
    FROM users u
)
SELECT user_activity.user_id, user_activity.name,
       user_activity.order_count, user_activity.total_spent
FROM user_activity
WHERE user_activity.order_count > 0
ORDER BY user_activity.total_spent DESC
`

type GetActiveUsersWithSubqueryRow struct {
	UserID     int64
	Name       string
	OrderCount int64
	TotalSpent interface{}
}

// CTE with nested subquery in SELECT
func (q *CteQueries) GetActiveUsersWithSubquery(ctx context.Context, db DBTX) ([]GetActiveUsersWithSubqueryRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.GetActiveUsersWithSubquery")
	defer tracer.End()
	rows, err := db.Query(ctx, GetActiveUsersWithSubquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveUsersWithSubqueryRow
	for rows.Next() {
		var i GetActiveUsersWithSubqueryRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.OrderCount,
			&i.TotalSpent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetAllEntities = `-- name: GetAllEntities :many
WITH all_entities AS (
    SELECT id as entity_id, name as entity_name, 'user' as entity_type, created_at
    FROM users
    UNION ALL
    SELECT id as entity_id, status as entity_name, 'order' as entity_type, created_at
    FROM orders
)
SELECT all_entities.entity_id, all_entities.entity_name,
       all_entities.entity_type, all_entities.created_at
FROM all_entities
ORDER BY all_entities.created_at DESC
`

type GetAllEntitiesRow struct {
	EntityID   int64
	EntityName string
	EntityType string
	CreatedAt  time.Time
}

// CTE with UNION ALL
func (q *CteQueries) GetAllEntities(ctx context.Context, db DBTX) ([]GetAllEntitiesRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.GetAllEntities")
	defer tracer.End()
	rows, err := db.Query(ctx, GetAllEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllEntitiesRow
	for rows.Next() {
		var i GetAllEntitiesRow
		if err := rows.Scan(
			&i.EntityID,
			&i.EntityName,
			&i.EntityType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetExclusiveHighValueUsers = `-- name: GetExclusiveHighValueUsers :many
WITH high_value_users AS (
    SELECT DISTINCT user_id FROM orders WHERE amount > 100
    EXCEPT
    SELECT DISTINCT user_id FROM orders WHERE status = 'cancelled'
)
SELECT u.id, u.name, u.email
FROM users u
INNER JOIN high_value_users hvu ON hvu.user_id = u.id
ORDER BY u.name
`

type GetExclusiveHighValueUsersRow struct {
	ID    int64
	Name  string
	Email string
}

// CTE with EXCEPT
func (q *CteQueries) GetExclusiveHighValueUsers(ctx context.Context, db DBTX) ([]GetExclusiveHighValueUsersRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.GetExclusiveHighValueUsers")
	defer tracer.End()
	rows, err := db.Query(ctx, GetExclusiveHighValueUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExclusiveHighValueUsersRow
	for rows.Next() {
		var i GetExclusiveHighValueUsersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetRevenueGrowth = `-- name: GetRevenueGrowth :many
WITH monthly_revenue AS (
    SELECT DATE_TRUNC('month', created_at)::DATE as month,
           COUNT(*) as order_count,
           SUM(amount) as revenue
    FROM orders
    WHERE created_at >= $1 AND created_at < $2
    GROUP BY DATE_TRUNC('month', created_at)
),
with_lag AS (
    SELECT month, order_count, revenue,
           LAG(revenue) OVER (ORDER BY month) as prev_revenue,
           LAG(order_count) OVER (ORDER BY month) as prev_order_count
    FROM monthly_revenue
),
with_growth AS (
    SELECT month, order_count, revenue,
           prev_revenue,
           CASE
               WHEN prev_revenue IS NOT NULL AND prev_revenue > 0
               THEN ROUND(((revenue - prev_revenue) / prev_revenue) * 100, 2)
               ELSE NULL
           END as growth_pct,
           SUM(revenue) OVER (ORDER BY month) as cumulative_revenue
    FROM with_lag
)
SELECT month, order_count, revenue, prev_revenue, growth_pct, cumulative_revenue
FROM with_growth
ORDER BY month
`

type GetRevenueGrowthParams struct {
	Since time.Time
	Until time.Time
}

type GetRevenueGrowthRow struct {
	Month             pgtype.Date
	OrderCount        int64
	Revenue           int64
	PrevRevenue       interface{}
	GrowthPct         interface{}
	CumulativeRevenue int64
}

// Generate a date series and compute month-over-month revenue with growth rate
func (q *CteQueries) GetRevenueGrowth(ctx context.Context, db DBTX, arg GetRevenueGrowthParams) ([]GetRevenueGrowthRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.GetRevenueGrowth")
	defer tracer.End()
	rows, err := db.Query(ctx, GetRevenueGrowth, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueGrowthRow
	for rows.Next() {
		var i GetRevenueGrowthRow
		if err := rows.Scan(
			&i.Month,
			&i.OrderCount,
			&i.Revenue,
			&i.PrevRevenue,
			&i.GrowthPct,
			&i.CumulativeRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetTopSpenders = `-- name: GetTopSpenders :many
WITH order_totals AS (
    SELECT user_id, COUNT(*) as order_count, COALESCE(SUM(amount), 0) as total_spent
    FROM orders
    GROUP BY user_id
    HAVING SUM(amount) >= $2
),
user_info AS (
    SELECT u.id, u.name, u.email, ot.order_count, ot.total_spent
    FROM users u
    INNER JOIN order_totals ot ON ot.user_id = u.id
)
SELECT id, name, email, order_count, total_spent FROM user_info
ORDER BY total_spent DESC
LIMIT $1
`

type GetTopSpendersParams struct {
	MaxResults int32
	MinSpent   decimal.Decimal
}

type GetTopSpendersRow struct {
	ID         int64
	Name       string
	Email      string
	OrderCount int64
	TotalSpent interface{}
}

func (q *CteQueries) GetTopSpenders(ctx context.Context, db DBTX, arg GetTopSpendersParams) ([]GetTopSpendersRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.GetTopSpenders")
	defer tracer.End()
	rows, err := db.Query(ctx, GetTopSpenders, arg.MaxResults, arg.MinSpent)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopSpendersRow
	for rows.Next() {
		var i GetTopSpendersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.OrderCount,
			&i.TotalSpent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserCohortRetention = `-- name: GetUserCohortRetention :many
WITH user_cohorts AS (
    SELECT users.id as user_id,
           DATE_TRUNC('month', users.created_at)::DATE as cohort_month
    FROM users
),
cohort_orders AS (
    SELECT user_cohorts.cohort_month,
           COUNT(DISTINCT user_cohorts.user_id) as active_users,
           COUNT(orders.id) as total_orders
    FROM user_cohorts
    INNER JOIN orders ON orders.user_id = user_cohorts.user_id
    WHERE orders.created_at >= user_cohorts.cohort_month
      AND orders.created_at < user_cohorts.cohort_month + INTERVAL '1 year'
    GROUP BY user_cohorts.cohort_month
)
SELECT cohort_month, active_users, total_orders FROM cohort_orders
ORDER BY cohort_month
`

type GetUserCohortRetentionRow struct {
	CohortMonth pgtype.Date
	ActiveUsers int64
	TotalOrders int64
}

// Cohort analysis: users grouped by signup month with ordering activity counts
func (q *CteQueries) GetUserCohortRetention(ctx context.Context, db DBTX) ([]GetUserCohortRetentionRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.GetUserCohortRetention")
	defer tracer.End()
	rows, err := db.Query(ctx, GetUserCohortRetention)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserCohortRetentionRow
	for rows.Next() {
		var i GetUserCohortRetentionRow
		if err := rows.Scan(&i.CohortMonth, &i.ActiveUsers, &i.TotalOrders); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserRank = `-- name: GetUserRank :one
WITH ranked_users AS (
    SELECT u.id as user_id, u.name, u.email,
           COALESCE(SUM(o.amount), 0) as total_spent,
           RANK() OVER (ORDER BY COALESCE(SUM(o.amount), 0) DESC) as spend_rank
    FROM users u
    LEFT JOIN orders o ON o.user_id = u.id
    GROUP BY u.id, u.name, u.email
)
SELECT user_id, name, email, total_spent, spend_rank FROM ranked_users
WHERE user_id = $1
`

type GetUserRankParams struct {
	UserID int64
}

type GetUserRankRow struct {
	UserID     int64
	Name       string
	Email      string
	TotalSpent interface{}
	SpendRank  int64
}

func (q *CteQueries) GetUserRank(ctx context.Context, db DBTX, arg GetUserRankParams) (*GetUserRankRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.GetUserRank")
	defer tracer.End()
	row := db.QueryRow(ctx, GetUserRank, arg.UserID)
	var i GetUserRankRow
	err := row.Scan(
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.TotalSpent,
		&i.SpendRank,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	return &i, err
}

const GetUserSpendingTiers = `-- name: GetUserSpendingTiers :many
WITH order_stats AS (
    SELECT user_id,
           COUNT(*) as order_count,
           COALESCE(SUM(amount), 0) as total_spent,
           COALESCE(AVG(amount), 0) as avg_order,
           COALESCE(MAX(amount), 0) as max_order,
           MIN(o.created_at) as first_order_at,
           MAX(o.created_at) as last_order_at
    FROM orders o
    GROUP BY user_id
),
spending_percentiles AS (
    SELECT user_id, order_count, total_spent, avg_order, max_order,
           first_order_at, last_order_at,
           PERCENT_RANK() OVER (ORDER BY total_spent) as spend_percentile,
           NTILE(4) OVER (ORDER BY total_spent) as spend_quartile
    FROM order_stats
),
tiered_users AS (
    SELECT sp.user_id, sp.order_count, sp.total_spent, sp.avg_order, sp.max_order, sp.first_order_at, sp.last_order_at, sp.spend_percentile, sp.spend_quartile,
           CASE
               WHEN spend_quartile = 4 THEN 'platinum'
               WHEN spend_quartile = 3 THEN 'gold'
               WHEN spend_quartile = 2 THEN 'silver'
               ELSE 'bronze'
           END as tier
    FROM spending_percentiles sp
)
SELECT u.id, u.name, u.email,
       tu.order_count, tu.total_spent, tu.avg_order, tu.max_order,
       tu.first_order_at, tu.last_order_at,
       tu.spend_percentile, tu.tier
FROM users u
INNER JOIN tiered_users tu ON tu.user_id = u.id
ORDER BY tu.total_spent DESC
`

type GetUserSpendingTiersRow struct {
	ID              int64
	Name            string
	Email           string
	OrderCount      int64
	TotalSpent      interface{}
	AvgOrder        interface{}
	MaxOrder        interface{}
	FirstOrderAt    interface{}
	LastOrderAt     interface{}
	SpendPercentile float64
	Tier            string
}

// Multi-step pipeline: aggregate → percentile → classify into tiers
func (q *CteQueries) GetUserSpendingTiers(ctx context.Context, db DBTX) ([]GetUserSpendingTiersRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.GetUserSpendingTiers")
	defer tracer.End()
	rows, err := db.Query(ctx, GetUserSpendingTiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserSpendingTiersRow
	for rows.Next() {
		var i GetUserSpendingTiersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.OrderCount,
			&i.TotalSpent,
			&i.AvgOrder,
			&i.MaxOrder,
			&i.FirstOrderAt,
			&i.LastOrderAt,
			&i.SpendPercentile,
			&i.Tier,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUserTiersBySubquery = `-- name: GetUserTiersBySubquery :many
WITH user_tiers AS (
    SELECT u.id as user_id, u.name,
           CASE
               WHEN (SELECT COUNT(*) FROM orders o WHERE o.user_id = u.id) > 10 THEN 'platinum'
               WHEN (SELECT COUNT(*) FROM orders o WHERE o.user_id = u.id) > 5 THEN 'gold'
               WHEN (SELECT COUNT(*) FROM orders o WHERE o.user_id = u.id) > 0 THEN 'silver'
               ELSE 'bronze'
           END as tier
    FROM users u
)
SELECT user_tiers.user_id, user_tiers.name, user_tiers.tier
FROM user_tiers
ORDER BY user_tiers.user_id
`

type GetUserTiersBySubqueryRow struct {
	UserID int64
	Name   string
	Tier   string
}

// CTE with CASE containing subquery
func (q *CteQueries) GetUserTiersBySubquery(ctx context.Context, db DBTX) ([]GetUserTiersBySubqueryRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.GetUserTiersBySubquery")
	defer tracer.End()
	rows, err := db.Query(ctx, GetUserTiersBySubquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTiersBySubqueryRow
	for rows.Next() {
		var i GetUserTiersBySubqueryRow
		if err := rows.Scan(&i.UserID, &i.Name, &i.Tier); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUsersWithOrderTotals = `-- name: GetUsersWithOrderTotals :many
WITH order_totals AS (
    SELECT user_id, COUNT(*) as order_count, COALESCE(SUM(amount), 0) as total_spent
    FROM orders
    GROUP BY user_id
)
SELECT u.id, u.name, u.email, ot.order_count, ot.total_spent
FROM users u
INNER JOIN order_totals ot ON ot.user_id = u.id
ORDER BY ot.total_spent DESC
`

type GetUsersWithOrderTotalsRow struct {
	ID         int64
	Name       string
	Email      string
	OrderCount int64
	TotalSpent interface{}
}

func (q *CteQueries) GetUsersWithOrderTotals(ctx context.Context, db DBTX) ([]GetUsersWithOrderTotalsRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.GetUsersWithOrderTotals")
	defer tracer.End()
	rows, err := db.Query(ctx, GetUsersWithOrderTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersWithOrderTotalsRow
	for rows.Next() {
		var i GetUsersWithOrderTotalsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.OrderCount,
			&i.TotalSpent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const GetUsersWithOrders = `-- name: GetUsersWithOrders :many
WITH active_users AS (
    SELECT id, name, email
    FROM users u
    WHERE EXISTS (SELECT 1 FROM orders WHERE user_id = u.id ORDER BY created_at DESC LIMIT 1)
)
SELECT active_users.id, active_users.name, active_users.email
FROM active_users
ORDER BY active_users.name
`

type GetUsersWithOrdersRow struct {
	ID    int64
	Name  string
	Email string
}

// CTE with EXISTS filter
func (q *CteQueries) GetUsersWithOrders(ctx context.Context, db DBTX) ([]GetUsersWithOrdersRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.GetUsersWithOrders")
	defer tracer.End()
	rows, err := db.Query(ctx, GetUsersWithOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersWithOrdersRow
	for rows.Next() {
		var i GetUsersWithOrdersRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const SearchUsersWithStats = `-- name: SearchUsersWithStats :many
WITH user_order_stats AS (
    SELECT orders.user_id,
           COUNT(*) as order_count,
           COALESCE(SUM(orders.amount), 0) as total_spent,
           MAX(orders.created_at) as last_order_at
    FROM orders
    GROUP BY orders.user_id
)
SELECT users.id, users.name, users.email, users.created_at,
       COALESCE(user_order_stats.order_count, 0) as order_count,
       COALESCE(user_order_stats.total_spent, 0) as total_spent,
       user_order_stats.last_order_at
FROM users
LEFT JOIN user_order_stats ON user_order_stats.user_id = users.id
WHERE 1 = 1
  AND users.name = $1 -- :if $1
  AND users.email = $2 -- :if $2
ORDER BY
  users.created_at DESC, -- :if $3
  users.name ASC
`

var _searchUsersWithStatsDynQ = dynCompile(SearchUsersWithStats)

type SearchUsersWithStatsParams struct {
	Name           *string
	Email          *string
	OrderByCreated bool
}

type SearchUsersWithStatsRow struct {
	ID          int64
	Name        string
	Email       string
	CreatedAt   time.Time
	OrderCount  int64
	TotalSpent  interface{}
	LastOrderAt interface{}
}

// CTE combined with dynamic filters on base table columns
func (q *CteQueries) SearchUsersWithStats(ctx context.Context, db DBTX, arg SearchUsersWithStatsParams) ([]SearchUsersWithStatsRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.SearchUsersWithStats")
	defer tracer.End()
	dynQuery, dynArgs := _searchUsersWithStatsDynQ.Build([]any{arg.Name, arg.Email, arg.OrderByCreated})
	rows, err := db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersWithStatsRow
	for rows.Next() {
		var i SearchUsersWithStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.OrderCount,
			&i.TotalSpent,
			&i.LastOrderAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const TransferUserOrders = `-- name: TransferUserOrders :many
WITH transferred AS (
    UPDATE orders
    SET user_id = $1
    WHERE user_id = $2 AND status = $3
    RETURNING id, user_id, amount, status, created_at
),
from_user AS (
    SELECT name as from_name FROM users WHERE id = $2
),
to_user AS (
    SELECT name as to_name FROM users WHERE id = $1
)
SELECT t.id, t.amount, t.status, t.created_at,
       fu.from_name, tu.to_name
FROM transferred t
CROSS JOIN from_user fu
CROSS JOIN to_user tu
ORDER BY t.created_at
`

type TransferUserOrdersParams struct {
	ToUserID   int64
	FromUserID int64
	Status     string
}

type TransferUserOrdersRow struct {
	ID        int64
	Amount    decimal.Decimal
	Status    string
	CreatedAt time.Time
	FromName  string
	ToName    string
}

// Writable CTE chain: update orders to new user, then return the transferred orders with both user names
func (q *CteQueries) TransferUserOrders(ctx context.Context, db DBTX, arg TransferUserOrdersParams) ([]TransferUserOrdersRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.TransferUserOrders")
	defer tracer.End()
	rows, err := db.Query(ctx, TransferUserOrders, arg.ToUserID, arg.FromUserID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransferUserOrdersRow
	for rows.Next() {
		var i TransferUserOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.Status,
			&i.CreatedAt,
			&i.FromName,
			&i.ToName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpsertAndReturnUser = `-- name: UpsertAndReturnUser :one
WITH upserted AS (
    INSERT INTO users (name, email)
    VALUES ($1, $2)
    ON CONFLICT (email) DO UPDATE SET name = EXCLUDED.name
    RETURNING id, name, email, created_at, phone
)
SELECT id, name, email, created_at, phone FROM upserted
`

type UpsertAndReturnUserParams struct {
	Name  string
	Email string
}

type UpsertAndReturnUserRow struct {
	ID        int64
	Name      string
	Email     string
	CreatedAt time.Time
	Phone     *string
}

func (q *CteQueries) UpsertAndReturnUser(ctx context.Context, db DBTX, arg UpsertAndReturnUserParams) (*UpsertAndReturnUserRow, error) {
	ctx, tracer := tracing.StartTracing(ctx, "CteQueries.UpsertAndReturnUser")
	defer tracer.End()
	row := db.QueryRow(ctx, UpsertAndReturnUser, arg.Name, arg.Email)
	var i UpsertAndReturnUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.Phone,
	)
	if errors.Is(err, pgx.ErrNoRows) {
		return nil, nil
	}
	return &i, err
}

type CteQuerier interface {
	DeleteUserAndReturnOrders(ctx context.Context, db DBTX, arg DeleteUserAndReturnOrdersParams) ([]DeleteUserAndReturnOrdersRow, error)
	// CTE with nested subquery in SELECT
	GetActiveUsersWithSubquery(ctx context.Context, db DBTX) ([]GetActiveUsersWithSubqueryRow, error)
	// CTE with UNION ALL
	GetAllEntities(ctx context.Context, db DBTX) ([]GetAllEntitiesRow, error)
	// CTE with EXCEPT
	GetExclusiveHighValueUsers(ctx context.Context, db DBTX) ([]GetExclusiveHighValueUsersRow, error)
	// Generate a date series and compute month-over-month revenue with growth rate
	GetRevenueGrowth(ctx context.Context, db DBTX, arg GetRevenueGrowthParams) ([]GetRevenueGrowthRow, error)
	GetTopSpenders(ctx context.Context, db DBTX, arg GetTopSpendersParams) ([]GetTopSpendersRow, error)
	// Cohort analysis: users grouped by signup month with ordering activity counts
	GetUserCohortRetention(ctx context.Context, db DBTX) ([]GetUserCohortRetentionRow, error)
	GetUserRank(ctx context.Context, db DBTX, arg GetUserRankParams) (*GetUserRankRow, error)
	// Multi-step pipeline: aggregate → percentile → classify into tiers
	GetUserSpendingTiers(ctx context.Context, db DBTX) ([]GetUserSpendingTiersRow, error)
	// CTE with CASE containing subquery
	GetUserTiersBySubquery(ctx context.Context, db DBTX) ([]GetUserTiersBySubqueryRow, error)
	GetUsersWithOrderTotals(ctx context.Context, db DBTX) ([]GetUsersWithOrderTotalsRow, error)
	// CTE with EXISTS filter
	GetUsersWithOrders(ctx context.Context, db DBTX) ([]GetUsersWithOrdersRow, error)
	// CTE combined with dynamic filters on base table columns
	SearchUsersWithStats(ctx context.Context, db DBTX, arg SearchUsersWithStatsParams) ([]SearchUsersWithStatsRow, error)
	// Writable CTE chain: update orders to new user, then return the transferred orders with both user names
	TransferUserOrders(ctx context.Context, db DBTX, arg TransferUserOrdersParams) ([]TransferUserOrdersRow, error)
	UpsertAndReturnUser(ctx context.Context, db DBTX, arg UpsertAndReturnUserParams) (*UpsertAndReturnUserRow, error)
}

var _ CteQuerier = (*CteQueries)(nil)
