// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"reflect"
	"strconv"
	"strings"
)

// DynamicSQL processes a SQL query with -- :if $N annotations.
// For each annotated line, it checks args[N-1] (N is 1-based, matching $N):
//   - nil pointer → skip the line
//   - false bool → skip the line
//   - otherwise → keep the line
//
// The original $N placeholders and args slice are kept unchanged —
// PostgreSQL accepts non-sequential $N (e.g. $1, $3 with no $2).
func DynamicSQL(query string, args []any) (string, []any) {
	lines := strings.Split(query, "\n")
	var kept []string
	skipNext := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Standalone block annotation: "-- :if $N"
		if strings.HasPrefix(trimmed, "-- :if $") {
			if rest := strings.TrimPrefix(trimmed, "-- :if $"); rest != "" {
				if n, err := strconv.Atoi(rest); err == nil {
					if n-1 < len(args) && !dynArgActive(args[n-1]) {
						skipNext = true
					}
					continue
				}
			}
		}

		if skipNext {
			skipNext = false
			continue
		}

		// Inline annotation: "... -- :if $N"
		if idx := strings.Index(line, " -- :if $"); idx != -1 {
			rest := strings.TrimSpace(line[idx+len(" -- :if $"):])
			if n, err := strconv.Atoi(rest); err == nil {
				if n-1 < len(args) && !dynArgActive(args[n-1]) {
					continue
				}
				line = strings.TrimRight(line[:idx], " \t")
			}
		}

		kept = append(kept, line)
	}

	return strings.Join(kept, "\n"), args
}

func dynArgActive(arg any) bool {
	if arg == nil {
		return false
	}
	v := reflect.ValueOf(arg)
	switch v.Kind() {
	case reflect.Ptr, reflect.Interface:
		return !v.IsNil()
	case reflect.Bool:
		return v.Bool()
	default:
		return true
	}
}
