//go:generate mockgen -source=$GOFILE -destination=mock/$GOFILE -package=mock

// Code generated by sqlc. DO NOT EDIT.
// source: search.sql

package db

import (
	"context"

	tracing "example"
)

func NewSearchQueries() *SearchQueries {
	return &SearchQueries{}
}

type SearchQueries struct {
}

const SearchUsers = `-- name: SearchUsers :many
SELECT id, name, email, created_at, phone FROM users
WHERE name = $1
  AND email = $2 -- :if $2
  AND phone = $3 -- :if $3
ORDER BY id ASC
`

type SearchUsersParams struct {
	Name  string
	Email *string
	Phone *string
}

func (q *SearchQueries) SearchUsers(ctx context.Context, db DBTX, arg SearchUsersParams) ([]*User, error) {
	ctx, tracer := tracing.StartTracing(ctx, "SearchQueries.SearchUsers")
	defer tracer.End()
	dynQuery, dynArgs := DynamicSQL(SearchUsers, []any{arg.Name, arg.Email, arg.Phone})
	rows, err := db.Query(ctx, dynQuery, dynArgs...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.CreatedAt,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type SearchQuerier interface {
	SearchUsers(ctx context.Context, db DBTX, arg SearchUsersParams) ([]*User, error)
}

var _ SearchQuerier = (*SearchQueries)(nil)
